"""new birthday model

Revision ID: 14c8183fe822
Revises: 
Create Date: 2026-04-13 19:45:19.049447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c8183fe822'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birthday_id', sa.Integer(), nullable=False),
    sa.Column('date_sent', sa.Date(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'birthday_id', 'date_sent', 'days_before', name='uq_sent_notification_once_per_day')
    )
    with op.batch_alter_table('sent_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sent_notifications_birthday_id'), ['birthday_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sent_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('birthdays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'first_name', 'last_name', name='uq_user_person')
    )
    with op.batch_alter_table('birthdays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_birthdays_user_id'), ['user_id'], unique=False)

    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'days_before', name='uq_user_notification_day')
    )
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_settings_user_id'), ['user_id'], unique=False)

    op.create_table('birthday_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('birthday_id', sa.Integer(), nullable=False),
    sa.Column('calendar_type', sa.Enum('gregorian', 'hebrew', name='calendar_type_enum'), nullable=False),
    sa.Column('gregorian_day', sa.Integer(), nullable=True),
    sa.Column('gregorian_month', sa.Integer(), nullable=True),
    sa.Column('gregorian_year', sa.Integer(), nullable=True),
    sa.Column('hebrew_day', sa.Integer(), nullable=True),
    sa.Column('hebrew_month', sa.Enum('tishrei', 'cheshvan', 'kislev', 'tevet', 'shevat', 'adar', 'adar_i', 'adar_ii', 'nisan', 'iyar', 'sivan', 'tammuz', 'av', 'elul', name='hebrew_month_enum'), nullable=True),
    sa.Column('hebrew_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['birthday_id'], ['birthdays.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birthday_id', 'calendar_type', name='uq_one_date_per_type')
    )
    with op.batch_alter_table('birthday_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_birthday_dates_birthday_id'), ['birthday_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthday_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_birthday_dates_birthday_id'))

    op.drop_table('birthday_dates')
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_settings_user_id'))

    op.drop_table('notification_settings')
    with op.batch_alter_table('birthdays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_birthdays_user_id'))

    op.drop_table('birthdays')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    with op.batch_alter_table('sent_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sent_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_sent_notifications_birthday_id'))

    op.drop_table('sent_notifications')
    # ### end Alembic commands ###
