"""add notification mode and is_derived

Revision ID: 1fae85b43b1b
Revises: 9a130df84526
Create Date: 2026-04-14 18:08:13.025267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fae85b43b1b'
down_revision: Union[str, None] = '9a130df84526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthday_dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_derived', sa.Boolean(), nullable=False))

    with op.batch_alter_table('birthdays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_calendar_mode', sa.Enum('gregorian', 'hebrew', 'both', name='notificationcalendarmode'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthdays', schema=None) as batch_op:
        batch_op.drop_column('notification_calendar_mode')

    with op.batch_alter_table('birthday_dates', schema=None) as batch_op:
        batch_op.drop_column('is_derived')

    # ### end Alembic commands ###
