"""add notification mode and is_derived

Revision ID: 5bac47de8cd7
Revises: 
Create Date: 2026-04-14 19:01:19.457384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bac47de8cd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birthday_date_id', sa.Integer(), nullable=False),
    sa.Column('date_sent', sa.Date(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'birthday_date_id', 'date_sent', 'days_before', name='uq_sent_notification_once_per_day')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_display_format', sa.Enum('gregorian', 'hebrew', 'both', name='datedisplayformat'), server_default='gregorian', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('birthdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), server_default='', nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('notification_calendar_mode', sa.Enum('gregorian', 'hebrew', 'both', name='notificationcalendarmode'), server_default='gregorian', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'first_name', 'last_name', name='uq_user_person')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'days_before', name='uq_user_notification_day')
    )
    op.create_table('birthday_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthday_id', sa.Integer(), nullable=False),
    sa.Column('calendar_type', sa.Enum('gregorian', 'hebrew', name='calendartype'), nullable=False),
    sa.Column('is_derived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('g_day', sa.Integer(), nullable=True),
    sa.Column('g_month', sa.Integer(), nullable=True),
    sa.Column('g_year', sa.Integer(), nullable=True),
    sa.Column('h_day', sa.Integer(), nullable=True),
    sa.Column('h_month', sa.Enum('tishrei', 'cheshvan', 'kislev', 'tevet', 'shevat', 'adar', 'adar_i', 'adar_ii', 'nisan', 'iyar', 'sivan', 'tammuz', 'av', 'elul', name='hebrewmonth'), nullable=True),
    sa.Column('h_year', sa.Integer(), nullable=True),
    sa.Column('adar_rule', sa.Enum('regular_to_adar_ii', 'regular_to_adar_i', name='adarrule'), server_default='regular_to_adar_ii', nullable=True),
    sa.ForeignKeyConstraint(['birthday_id'], ['birthdays.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birthday_id', 'calendar_type', name='uq_birthday_one_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthday_dates')
    op.drop_table('notification_settings')
    op.drop_table('birthdays')
    op.drop_table('users')
    op.drop_table('sent_notifications')
    # ### end Alembic commands ###
