"""add hebrew support

Revision ID: 67310b201e3a
Revises: 
Create Date: 2026-04-14 16:34:57.694265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67310b201e3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birthday_date_id', sa.Integer(), nullable=False),
    sa.Column('date_sent', sa.Date(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'birthday_date_id', 'date_sent', 'days_before', name='uq_sent_notification_once_per_day')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_display_format', sa.Enum('gregorian', 'hebrew', 'both', name='datedisplayformat'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('birthdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'first_name', 'last_name', name='uq_user_person')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'days_before', name='uq_user_notification_day')
    )
    op.create_table('birthday_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthday_id', sa.Integer(), nullable=False),
    sa.Column('calendar_type', sa.Enum('gregorian', 'hebrew', name='calendartype'), nullable=False),
    sa.Column('g_day', sa.Integer(), nullable=True),
    sa.Column('g_month', sa.Integer(), nullable=True),
    sa.Column('g_year', sa.Integer(), nullable=True),
    sa.Column('h_day', sa.Integer(), nullable=True),
    sa.Column('h_month', sa.Enum('tishrei', 'cheshvan', 'kislev', 'tevet', 'shevat', 'adar', 'adar_i', 'adar_ii', 'nisan', 'iyar', 'sivan', 'tammuz', 'av', 'elul', name='hebrewmonth'), nullable=True),
    sa.Column('h_year', sa.Integer(), nullable=True),
    sa.Column('adar_rule', sa.Enum('regular_to_adar_ii', 'regular_to_adar_i', name='adarrule'), nullable=True),
    sa.ForeignKeyConstraint(['birthday_id'], ['birthdays.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birthday_id', 'calendar_type', name='uq_birthday_one_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthday_dates')
    op.drop_table('notification_settings')
    op.drop_table('birthdays')
    op.drop_table('users')
    op.drop_table('sent_notifications')
    # ### end Alembic commands ###
