"""add description to birthdays

Revision ID: 6ee23a2cc81a
Revises: 7a6ce8964d4a
Create Date: 2026-04-13 16:35:00.036394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee23a2cc81a'
down_revision: Union[str, None] = '7a6ce8964d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("birthdays", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "description",
                sa.String(),
                nullable=False,
                server_default="",
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthdays', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
